POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jules Verne",
  "number" : "123 456 789"
}

### Bad request - no name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number" : "123 456 789"
}

### Bad request - no number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jules Verne"
}

### get all
GET http://localhost:3001/api/persons